package com.ivana.controller;

import static org.junit.Assert.*;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;

import org.junit.Test;

import com.ivana.model.Repository;
import com.ivana.model.User;

public class JsonHelperTest {
  
	private final String repositories = "[\r\n" + 
			"  {\r\n" + 
			"    \"id\": 18221276,\r\n" + 
			"    \"name\": \"git-consortium\",\r\n" + 
			"    \"full_name\": \"octocat/git-consortium\",\r\n" + 
			"    \"owner\": {\r\n" + 
			"      \"login\": \"octocat\",\r\n" + 
			"      \"id\": 583231,\r\n" + 
			"      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/583231?v=4\",\r\n" + 
			"      \"gravatar_id\": \"\",\r\n" + 
			"      \"url\": \"https://api.github.com/users/octocat\",\r\n" + 
			"      \"html_url\": \"https://github.com/octocat\",\r\n" + 
			"      \"followers_url\": \"https://api.github.com/users/octocat/followers\",\r\n" + 
			"      \"following_url\": \"https://api.github.com/users/octocat/following{/other_user}\",\r\n" + 
			"      \"gists_url\": \"https://api.github.com/users/octocat/gists{/gist_id}\",\r\n" + 
			"      \"starred_url\": \"https://api.github.com/users/octocat/starred{/owner}{/repo}\",\r\n" + 
			"      \"subscriptions_url\": \"https://api.github.com/users/octocat/subscriptions\",\r\n" + 
			"      \"organizations_url\": \"https://api.github.com/users/octocat/orgs\",\r\n" + 
			"      \"repos_url\": \"https://api.github.com/users/octocat/repos\",\r\n" + 
			"      \"events_url\": \"https://api.github.com/users/octocat/events{/privacy}\",\r\n" + 
			"      \"received_events_url\": \"https://api.github.com/users/octocat/received_events\",\r\n" + 
			"      \"type\": \"User\",\r\n" + 
			"      \"site_admin\": false\r\n" + 
			"    },\r\n" + 
			"    \"private\": false,\r\n" + 
			"    \"html_url\": \"https://github.com/octocat/git-consortium\",\r\n" + 
			"    \"description\": \"This repo is for demonstration purposes only.\",\r\n" + 
			"    \"fork\": false,\r\n" + 
			"    \"url\": \"https://api.github.com/repos/octocat/git-consortium\",\r\n" + 
			"    \"forks_url\": \"https://api.github.com/repos/octocat/git-consortium/forks\",\r\n" + 
			"    \"keys_url\": \"https://api.github.com/repos/octocat/git-consortium/keys{/key_id}\",\r\n" + 
			"    \"collaborators_url\": \"https://api.github.com/repos/octocat/git-consortium/collaborators{/collaborator}\",\r\n" + 
			"    \"teams_url\": \"https://api.github.com/repos/octocat/git-consortium/teams\",\r\n" + 
			"    \"hooks_url\": \"https://api.github.com/repos/octocat/git-consortium/hooks\",\r\n" + 
			"    \"issue_events_url\": \"https://api.github.com/repos/octocat/git-consortium/issues/events{/number}\",\r\n" + 
			"    \"events_url\": \"https://api.github.com/repos/octocat/git-consortium/events\",\r\n" + 
			"    \"assignees_url\": \"https://api.github.com/repos/octocat/git-consortium/assignees{/user}\",\r\n" + 
			"    \"branches_url\": \"https://api.github.com/repos/octocat/git-consortium/branches{/branch}\",\r\n" + 
			"    \"tags_url\": \"https://api.github.com/repos/octocat/git-consortium/tags\",\r\n" + 
			"    \"blobs_url\": \"https://api.github.com/repos/octocat/git-consortium/git/blobs{/sha}\",\r\n" + 
			"    \"git_tags_url\": \"https://api.github.com/repos/octocat/git-consortium/git/tags{/sha}\",\r\n" + 
			"    \"git_refs_url\": \"https://api.github.com/repos/octocat/git-consortium/git/refs{/sha}\",\r\n" + 
			"    \"trees_url\": \"https://api.github.com/repos/octocat/git-consortium/git/trees{/sha}\",\r\n" + 
			"    \"statuses_url\": \"https://api.github.com/repos/octocat/git-consortium/statuses/{sha}\",\r\n" + 
			"    \"languages_url\": \"https://api.github.com/repos/octocat/git-consortium/languages\",\r\n" + 
			"    \"stargazers_url\": \"https://api.github.com/repos/octocat/git-consortium/stargazers\",\r\n" + 
			"    \"contributors_url\": \"https://api.github.com/repos/octocat/git-consortium/contributors\",\r\n" + 
			"    \"subscribers_url\": \"https://api.github.com/repos/octocat/git-consortium/subscribers\",\r\n" + 
			"    \"subscription_url\": \"https://api.github.com/repos/octocat/git-consortium/subscription\",\r\n" + 
			"    \"commits_url\": \"https://api.github.com/repos/octocat/git-consortium/commits{/sha}\",\r\n" + 
			"    \"git_commits_url\": \"https://api.github.com/repos/octocat/git-consortium/git/commits{/sha}\",\r\n" + 
			"    \"comments_url\": \"https://api.github.com/repos/octocat/git-consortium/comments{/number}\",\r\n" + 
			"    \"issue_comment_url\": \"https://api.github.com/repos/octocat/git-consortium/issues/comments{/number}\",\r\n" + 
			"    \"contents_url\": \"https://api.github.com/repos/octocat/git-consortium/contents/{+path}\",\r\n" + 
			"    \"compare_url\": \"https://api.github.com/repos/octocat/git-consortium/compare/{base}...{head}\",\r\n" + 
			"    \"merges_url\": \"https://api.github.com/repos/octocat/git-consortium/merges\",\r\n" + 
			"    \"archive_url\": \"https://api.github.com/repos/octocat/git-consortium/{archive_format}{/ref}\",\r\n" + 
			"    \"downloads_url\": \"https://api.github.com/repos/octocat/git-consortium/downloads\",\r\n" + 
			"    \"issues_url\": \"https://api.github.com/repos/octocat/git-consortium/issues{/number}\",\r\n" + 
			"    \"pulls_url\": \"https://api.github.com/repos/octocat/git-consortium/pulls{/number}\",\r\n" + 
			"    \"milestones_url\": \"https://api.github.com/repos/octocat/git-consortium/milestones{/number}\",\r\n" + 
			"    \"notifications_url\": \"https://api.github.com/repos/octocat/git-consortium/notifications{?since,all,participating}\",\r\n" + 
			"    \"labels_url\": \"https://api.github.com/repos/octocat/git-consortium/labels{/name}\",\r\n" + 
			"    \"releases_url\": \"https://api.github.com/repos/octocat/git-consortium/releases{/id}\",\r\n" + 
			"    \"deployments_url\": \"https://api.github.com/repos/octocat/git-consortium/deployments\",\r\n" + 
			"    \"created_at\": \"2014-03-28T17:55:38Z\",\r\n" + 
			"    \"updated_at\": \"2017-07-06T04:15:11Z\",\r\n" + 
			"    \"pushed_at\": \"2016-10-30T13:43:30Z\",\r\n" + 
			"    \"git_url\": \"git://github.com/octocat/git-consortium.git\",\r\n" + 
			"    \"ssh_url\": \"git@github.com:octocat/git-consortium.git\",\r\n" + 
			"    \"clone_url\": \"https://github.com/octocat/git-consortium.git\",\r\n" + 
			"    \"svn_url\": \"https://github.com/octocat/git-consortium\",\r\n" + 
			"    \"homepage\": null,\r\n" + 
			"    \"size\": 190,\r\n" + 
			"    \"stargazers_count\": 8,\r\n" + 
			"    \"watchers_count\": 8,\r\n" + 
			"    \"language\": null,\r\n" + 
			"    \"has_issues\": true,\r\n" + 
			"    \"has_projects\": true,\r\n" + 
			"    \"has_downloads\": true,\r\n" + 
			"    \"has_wiki\": true,\r\n" + 
			"    \"has_pages\": false,\r\n" + 
			"    \"forks_count\": 26,\r\n" + 
			"    \"mirror_url\": null,\r\n" + 
			"    \"open_issues_count\": 4,\r\n" + 
			"    \"forks\": 26,\r\n" + 
			"    \"open_issues\": 4,\r\n" + 
			"    \"watchers\": 8,\r\n" + 
			"    \"default_branch\": \"master\"\r\n" + 
			"  },\r\n" + 
			"  {\r\n" + 
			"    \"id\": 20978623,\r\n" + 
			"    \"name\": \"hello-worId\",\r\n" + 
			"    \"full_name\": \"octocat/hello-worId\",\r\n" + 
			"    \"owner\": {\r\n" + 
			"      \"login\": \"octocat\",\r\n" + 
			"      \"id\": 583231,\r\n" + 
			"      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/583231?v=4\",\r\n" + 
			"      \"gravatar_id\": \"\",\r\n" + 
			"      \"url\": \"https://api.github.com/users/octocat\",\r\n" + 
			"      \"html_url\": \"https://github.com/octocat\",\r\n" + 
			"      \"followers_url\": \"https://api.github.com/users/octocat/followers\",\r\n" + 
			"      \"following_url\": \"https://api.github.com/users/octocat/following{/other_user}\",\r\n" + 
			"      \"gists_url\": \"https://api.github.com/users/octocat/gists{/gist_id}\",\r\n" + 
			"      \"starred_url\": \"https://api.github.com/users/octocat/starred{/owner}{/repo}\",\r\n" + 
			"      \"subscriptions_url\": \"https://api.github.com/users/octocat/subscriptions\",\r\n" + 
			"      \"organizations_url\": \"https://api.github.com/users/octocat/orgs\",\r\n" + 
			"      \"repos_url\": \"https://api.github.com/users/octocat/repos\",\r\n" + 
			"      \"events_url\": \"https://api.github.com/users/octocat/events{/privacy}\",\r\n" + 
			"      \"received_events_url\": \"https://api.github.com/users/octocat/received_events\",\r\n" + 
			"      \"type\": \"User\",\r\n" + 
			"      \"site_admin\": false\r\n" + 
			"    },\r\n" + 
			"    \"private\": false,\r\n" + 
			"    \"html_url\": \"https://github.com/octocat/hello-worId\",\r\n" + 
			"    \"description\": \"My first repository on GitHub.\",\r\n" + 
			"    \"fork\": false,\r\n" + 
			"    \"url\": \"https://api.github.com/repos/octocat/hello-worId\",\r\n" + 
			"    \"forks_url\": \"https://api.github.com/repos/octocat/hello-worId/forks\",\r\n" + 
			"    \"keys_url\": \"https://api.github.com/repos/octocat/hello-worId/keys{/key_id}\",\r\n" + 
			"    \"collaborators_url\": \"https://api.github.com/repos/octocat/hello-worId/collaborators{/collaborator}\",\r\n" + 
			"    \"teams_url\": \"https://api.github.com/repos/octocat/hello-worId/teams\",\r\n" + 
			"    \"hooks_url\": \"https://api.github.com/repos/octocat/hello-worId/hooks\",\r\n" + 
			"    \"issue_events_url\": \"https://api.github.com/repos/octocat/hello-worId/issues/events{/number}\",\r\n" + 
			"    \"events_url\": \"https://api.github.com/repos/octocat/hello-worId/events\",\r\n" + 
			"    \"assignees_url\": \"https://api.github.com/repos/octocat/hello-worId/assignees{/user}\",\r\n" + 
			"    \"branches_url\": \"https://api.github.com/repos/octocat/hello-worId/branches{/branch}\",\r\n" + 
			"    \"tags_url\": \"https://api.github.com/repos/octocat/hello-worId/tags\",\r\n" + 
			"    \"blobs_url\": \"https://api.github.com/repos/octocat/hello-worId/git/blobs{/sha}\",\r\n" + 
			"    \"git_tags_url\": \"https://api.github.com/repos/octocat/hello-worId/git/tags{/sha}\",\r\n" + 
			"    \"git_refs_url\": \"https://api.github.com/repos/octocat/hello-worId/git/refs{/sha}\",\r\n" + 
			"    \"trees_url\": \"https://api.github.com/repos/octocat/hello-worId/git/trees{/sha}\",\r\n" + 
			"    \"statuses_url\": \"https://api.github.com/repos/octocat/hello-worId/statuses/{sha}\",\r\n" + 
			"    \"languages_url\": \"https://api.github.com/repos/octocat/hello-worId/languages\",\r\n" + 
			"    \"stargazers_url\": \"https://api.github.com/repos/octocat/hello-worId/stargazers\",\r\n" + 
			"    \"contributors_url\": \"https://api.github.com/repos/octocat/hello-worId/contributors\",\r\n" + 
			"    \"subscribers_url\": \"https://api.github.com/repos/octocat/hello-worId/subscribers\",\r\n" + 
			"    \"subscription_url\": \"https://api.github.com/repos/octocat/hello-worId/subscription\",\r\n" + 
			"    \"commits_url\": \"https://api.github.com/repos/octocat/hello-worId/commits{/sha}\",\r\n" + 
			"    \"git_commits_url\": \"https://api.github.com/repos/octocat/hello-worId/git/commits{/sha}\",\r\n" + 
			"    \"comments_url\": \"https://api.github.com/repos/octocat/hello-worId/comments{/number}\",\r\n" + 
			"    \"issue_comment_url\": \"https://api.github.com/repos/octocat/hello-worId/issues/comments{/number}\",\r\n" + 
			"    \"contents_url\": \"https://api.github.com/repos/octocat/hello-worId/contents/{+path}\",\r\n" + 
			"    \"compare_url\": \"https://api.github.com/repos/octocat/hello-worId/compare/{base}...{head}\",\r\n" + 
			"    \"merges_url\": \"https://api.github.com/repos/octocat/hello-worId/merges\",\r\n" + 
			"    \"archive_url\": \"https://api.github.com/repos/octocat/hello-worId/{archive_format}{/ref}\",\r\n" + 
			"    \"downloads_url\": \"https://api.github.com/repos/octocat/hello-worId/downloads\",\r\n" + 
			"    \"issues_url\": \"https://api.github.com/repos/octocat/hello-worId/issues{/number}\",\r\n" + 
			"    \"pulls_url\": \"https://api.github.com/repos/octocat/hello-worId/pulls{/number}\",\r\n" + 
			"    \"milestones_url\": \"https://api.github.com/repos/octocat/hello-worId/milestones{/number}\",\r\n" + 
			"    \"notifications_url\": \"https://api.github.com/repos/octocat/hello-worId/notifications{?since,all,participating}\",\r\n" + 
			"    \"labels_url\": \"https://api.github.com/repos/octocat/hello-worId/labels{/name}\",\r\n" + 
			"    \"releases_url\": \"https://api.github.com/repos/octocat/hello-worId/releases{/id}\",\r\n" + 
			"    \"deployments_url\": \"https://api.github.com/repos/octocat/hello-worId/deployments\",\r\n" + 
			"    \"created_at\": \"2014-06-18T21:26:19Z\",\r\n" + 
			"    \"updated_at\": \"2017-07-20T13:09:18Z\",\r\n" + 
			"    \"pushed_at\": \"2016-11-04T14:12:56Z\",\r\n" + 
			"    \"git_url\": \"git://github.com/octocat/hello-worId.git\",\r\n" + 
			"    \"ssh_url\": \"git@github.com:octocat/hello-worId.git\",\r\n" + 
			"    \"clone_url\": \"https://github.com/octocat/hello-worId.git\",\r\n" + 
			"    \"svn_url\": \"https://github.com/octocat/hello-worId\",\r\n" + 
			"    \"homepage\": null,\r\n" + 
			"    \"size\": 160,\r\n" + 
			"    \"stargazers_count\": 14,\r\n" + 
			"    \"watchers_count\": 14,\r\n" + 
			"    \"language\": null,\r\n" + 
			"    \"has_issues\": true,\r\n" + 
			"    \"has_projects\": true,\r\n" + 
			"    \"has_downloads\": true,\r\n" + 
			"    \"has_wiki\": true,\r\n" + 
			"    \"has_pages\": false,\r\n" + 
			"    \"forks_count\": 37,\r\n" + 
			"    \"mirror_url\": null,\r\n" + 
			"    \"open_issues_count\": 5,\r\n" + 
			"    \"forks\": 37,\r\n" + 
			"    \"open_issues\": 5,\r\n" + 
			"    \"watchers\": 14,\r\n" + 
			"    \"default_branch\": \"master\"\r\n" + 
			"  },\r\n" + 
			"  {\r\n" + 
			"    \"id\": 1296269,\r\n" + 
			"    \"name\": \"Hello-World\",\r\n" + 
			"    \"full_name\": \"octocat/Hello-World\",\r\n" + 
			"    \"owner\": {\r\n" + 
			"      \"login\": \"octocat\",\r\n" + 
			"      \"id\": 583231,\r\n" + 
			"      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/583231?v=4\",\r\n" + 
			"      \"gravatar_id\": \"\",\r\n" + 
			"      \"url\": \"https://api.github.com/users/octocat\",\r\n" + 
			"      \"html_url\": \"https://github.com/octocat\",\r\n" + 
			"      \"followers_url\": \"https://api.github.com/users/octocat/followers\",\r\n" + 
			"      \"following_url\": \"https://api.github.com/users/octocat/following{/other_user}\",\r\n" + 
			"      \"gists_url\": \"https://api.github.com/users/octocat/gists{/gist_id}\",\r\n" + 
			"      \"starred_url\": \"https://api.github.com/users/octocat/starred{/owner}{/repo}\",\r\n" + 
			"      \"subscriptions_url\": \"https://api.github.com/users/octocat/subscriptions\",\r\n" + 
			"      \"organizations_url\": \"https://api.github.com/users/octocat/orgs\",\r\n" + 
			"      \"repos_url\": \"https://api.github.com/users/octocat/repos\",\r\n" + 
			"      \"events_url\": \"https://api.github.com/users/octocat/events{/privacy}\",\r\n" + 
			"      \"received_events_url\": \"https://api.github.com/users/octocat/received_events\",\r\n" + 
			"      \"type\": \"User\",\r\n" + 
			"      \"site_admin\": false\r\n" + 
			"    },\r\n" + 
			"    \"private\": false,\r\n" + 
			"    \"html_url\": \"https://github.com/octocat/Hello-World\",\r\n" + 
			"    \"description\": \"My first repository on GitHub!\",\r\n" + 
			"    \"fork\": false,\r\n" + 
			"    \"url\": \"https://api.github.com/repos/octocat/Hello-World\",\r\n" + 
			"    \"forks_url\": \"https://api.github.com/repos/octocat/Hello-World/forks\",\r\n" + 
			"    \"keys_url\": \"https://api.github.com/repos/octocat/Hello-World/keys{/key_id}\",\r\n" + 
			"    \"collaborators_url\": \"https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}\",\r\n" + 
			"    \"teams_url\": \"https://api.github.com/repos/octocat/Hello-World/teams\",\r\n" + 
			"    \"hooks_url\": \"https://api.github.com/repos/octocat/Hello-World/hooks\",\r\n" + 
			"    \"issue_events_url\": \"https://api.github.com/repos/octocat/Hello-World/issues/events{/number}\",\r\n" + 
			"    \"events_url\": \"https://api.github.com/repos/octocat/Hello-World/events\",\r\n" + 
			"    \"assignees_url\": \"https://api.github.com/repos/octocat/Hello-World/assignees{/user}\",\r\n" + 
			"    \"branches_url\": \"https://api.github.com/repos/octocat/Hello-World/branches{/branch}\",\r\n" + 
			"    \"tags_url\": \"https://api.github.com/repos/octocat/Hello-World/tags\",\r\n" + 
			"    \"blobs_url\": \"https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}\",\r\n" + 
			"    \"git_tags_url\": \"https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}\",\r\n" + 
			"    \"git_refs_url\": \"https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}\",\r\n" + 
			"    \"trees_url\": \"https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}\",\r\n" + 
			"    \"statuses_url\": \"https://api.github.com/repos/octocat/Hello-World/statuses/{sha}\",\r\n" + 
			"    \"languages_url\": \"https://api.github.com/repos/octocat/Hello-World/languages\",\r\n" + 
			"    \"stargazers_url\": \"https://api.github.com/repos/octocat/Hello-World/stargazers\",\r\n" + 
			"    \"contributors_url\": \"https://api.github.com/repos/octocat/Hello-World/contributors\",\r\n" + 
			"    \"subscribers_url\": \"https://api.github.com/repos/octocat/Hello-World/subscribers\",\r\n" + 
			"    \"subscription_url\": \"https://api.github.com/repos/octocat/Hello-World/subscription\",\r\n" + 
			"    \"commits_url\": \"https://api.github.com/repos/octocat/Hello-World/commits{/sha}\",\r\n" + 
			"    \"git_commits_url\": \"https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}\",\r\n" + 
			"    \"comments_url\": \"https://api.github.com/repos/octocat/Hello-World/comments{/number}\",\r\n" + 
			"    \"issue_comment_url\": \"https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}\",\r\n" + 
			"    \"contents_url\": \"https://api.github.com/repos/octocat/Hello-World/contents/{+path}\",\r\n" + 
			"    \"compare_url\": \"https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}\",\r\n" + 
			"    \"merges_url\": \"https://api.github.com/repos/octocat/Hello-World/merges\",\r\n" + 
			"    \"archive_url\": \"https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}\",\r\n" + 
			"    \"downloads_url\": \"https://api.github.com/repos/octocat/Hello-World/downloads\",\r\n" + 
			"    \"issues_url\": \"https://api.github.com/repos/octocat/Hello-World/issues{/number}\",\r\n" + 
			"    \"pulls_url\": \"https://api.github.com/repos/octocat/Hello-World/pulls{/number}\",\r\n" + 
			"    \"milestones_url\": \"https://api.github.com/repos/octocat/Hello-World/milestones{/number}\",\r\n" + 
			"    \"notifications_url\": \"https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}\",\r\n" + 
			"    \"labels_url\": \"https://api.github.com/repos/octocat/Hello-World/labels{/name}\",\r\n" + 
			"    \"releases_url\": \"https://api.github.com/repos/octocat/Hello-World/releases{/id}\",\r\n" + 
			"    \"deployments_url\": \"https://api.github.com/repos/octocat/Hello-World/deployments\",\r\n" + 
			"    \"created_at\": \"2011-01-26T19:01:12Z\",\r\n" + 
			"    \"updated_at\": \"2017-09-23T11:53:14Z\",\r\n" + 
			"    \"pushed_at\": \"2017-09-04T00:57:08Z\",\r\n" + 
			"    \"git_url\": \"git://github.com/octocat/Hello-World.git\",\r\n" + 
			"    \"ssh_url\": \"git@github.com:octocat/Hello-World.git\",\r\n" + 
			"    \"clone_url\": \"https://github.com/octocat/Hello-World.git\",\r\n" + 
			"    \"svn_url\": \"https://github.com/octocat/Hello-World\",\r\n" + 
			"    \"homepage\": \"\",\r\n" + 
			"    \"size\": 578,\r\n" + 
			"    \"stargazers_count\": 1433,\r\n" + 
			"    \"watchers_count\": 1433,\r\n" + 
			"    \"language\": null,\r\n" + 
			"    \"has_issues\": true,\r\n" + 
			"    \"has_projects\": true,\r\n" + 
			"    \"has_downloads\": true,\r\n" + 
			"    \"has_wiki\": true,\r\n" + 
			"    \"has_pages\": false,\r\n" + 
			"    \"forks_count\": 1184,\r\n" + 
			"    \"mirror_url\": null,\r\n" + 
			"    \"open_issues_count\": 260,\r\n" + 
			"    \"forks\": 1184,\r\n" + 
			"    \"open_issues\": 260,\r\n" + 
			"    \"watchers\": 1433,\r\n" + 
			"    \"default_branch\": \"master\"\r\n" + 
			"  },\r\n" + 
			"  {\r\n" + 
			"    \"id\": 64778136,\r\n" + 
			"    \"name\": \"linguist\",\r\n" + 
			"    \"full_name\": \"octocat/linguist\",\r\n" + 
			"    \"owner\": {\r\n" + 
			"      \"login\": \"octocat\",\r\n" + 
			"      \"id\": 583231,\r\n" + 
			"      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/583231?v=4\",\r\n" + 
			"      \"gravatar_id\": \"\",\r\n" + 
			"      \"url\": \"https://api.github.com/users/octocat\",\r\n" + 
			"      \"html_url\": \"https://github.com/octocat\",\r\n" + 
			"      \"followers_url\": \"https://api.github.com/users/octocat/followers\",\r\n" + 
			"      \"following_url\": \"https://api.github.com/users/octocat/following{/other_user}\",\r\n" + 
			"      \"gists_url\": \"https://api.github.com/users/octocat/gists{/gist_id}\",\r\n" + 
			"      \"starred_url\": \"https://api.github.com/users/octocat/starred{/owner}{/repo}\",\r\n" + 
			"      \"subscriptions_url\": \"https://api.github.com/users/octocat/subscriptions\",\r\n" + 
			"      \"organizations_url\": \"https://api.github.com/users/octocat/orgs\",\r\n" + 
			"      \"repos_url\": \"https://api.github.com/users/octocat/repos\",\r\n" + 
			"      \"events_url\": \"https://api.github.com/users/octocat/events{/privacy}\",\r\n" + 
			"      \"received_events_url\": \"https://api.github.com/users/octocat/received_events\",\r\n" + 
			"      \"type\": \"User\",\r\n" + 
			"      \"site_admin\": false\r\n" + 
			"    },\r\n" + 
			"    \"private\": false,\r\n" + 
			"    \"html_url\": \"https://github.com/octocat/linguist\",\r\n" + 
			"    \"description\": \"Language Savant. If your repository's language is being reported incorrectly, send us a pull request!\",\r\n" + 
			"    \"fork\": true,\r\n" + 
			"    \"url\": \"https://api.github.com/repos/octocat/linguist\",\r\n" + 
			"    \"forks_url\": \"https://api.github.com/repos/octocat/linguist/forks\",\r\n" + 
			"    \"keys_url\": \"https://api.github.com/repos/octocat/linguist/keys{/key_id}\",\r\n" + 
			"    \"collaborators_url\": \"https://api.github.com/repos/octocat/linguist/collaborators{/collaborator}\",\r\n" + 
			"    \"teams_url\": \"https://api.github.com/repos/octocat/linguist/teams\",\r\n" + 
			"    \"hooks_url\": \"https://api.github.com/repos/octocat/linguist/hooks\",\r\n" + 
			"    \"issue_events_url\": \"https://api.github.com/repos/octocat/linguist/issues/events{/number}\",\r\n" + 
			"    \"events_url\": \"https://api.github.com/repos/octocat/linguist/events\",\r\n" + 
			"    \"assignees_url\": \"https://api.github.com/repos/octocat/linguist/assignees{/user}\",\r\n" + 
			"    \"branches_url\": \"https://api.github.com/repos/octocat/linguist/branches{/branch}\",\r\n" + 
			"    \"tags_url\": \"https://api.github.com/repos/octocat/linguist/tags\",\r\n" + 
			"    \"blobs_url\": \"https://api.github.com/repos/octocat/linguist/git/blobs{/sha}\",\r\n" + 
			"    \"git_tags_url\": \"https://api.github.com/repos/octocat/linguist/git/tags{/sha}\",\r\n" + 
			"    \"git_refs_url\": \"https://api.github.com/repos/octocat/linguist/git/refs{/sha}\",\r\n" + 
			"    \"trees_url\": \"https://api.github.com/repos/octocat/linguist/git/trees{/sha}\",\r\n" + 
			"    \"statuses_url\": \"https://api.github.com/repos/octocat/linguist/statuses/{sha}\",\r\n" + 
			"    \"languages_url\": \"https://api.github.com/repos/octocat/linguist/languages\",\r\n" + 
			"    \"stargazers_url\": \"https://api.github.com/repos/octocat/linguist/stargazers\",\r\n" + 
			"    \"contributors_url\": \"https://api.github.com/repos/octocat/linguist/contributors\",\r\n" + 
			"    \"subscribers_url\": \"https://api.github.com/repos/octocat/linguist/subscribers\",\r\n" + 
			"    \"subscription_url\": \"https://api.github.com/repos/octocat/linguist/subscription\",\r\n" + 
			"    \"commits_url\": \"https://api.github.com/repos/octocat/linguist/commits{/sha}\",\r\n" + 
			"    \"git_commits_url\": \"https://api.github.com/repos/octocat/linguist/git/commits{/sha}\",\r\n" + 
			"    \"comments_url\": \"https://api.github.com/repos/octocat/linguist/comments{/number}\",\r\n" + 
			"    \"issue_comment_url\": \"https://api.github.com/repos/octocat/linguist/issues/comments{/number}\",\r\n" + 
			"    \"contents_url\": \"https://api.github.com/repos/octocat/linguist/contents/{+path}\",\r\n" + 
			"    \"compare_url\": \"https://api.github.com/repos/octocat/linguist/compare/{base}...{head}\",\r\n" + 
			"    \"merges_url\": \"https://api.github.com/repos/octocat/linguist/merges\",\r\n" + 
			"    \"archive_url\": \"https://api.github.com/repos/octocat/linguist/{archive_format}{/ref}\",\r\n" + 
			"    \"downloads_url\": \"https://api.github.com/repos/octocat/linguist/downloads\",\r\n" + 
			"    \"issues_url\": \"https://api.github.com/repos/octocat/linguist/issues{/number}\",\r\n" + 
			"    \"pulls_url\": \"https://api.github.com/repos/octocat/linguist/pulls{/number}\",\r\n" + 
			"    \"milestones_url\": \"https://api.github.com/repos/octocat/linguist/milestones{/number}\",\r\n" + 
			"    \"notifications_url\": \"https://api.github.com/repos/octocat/linguist/notifications{?since,all,participating}\",\r\n" + 
			"    \"labels_url\": \"https://api.github.com/repos/octocat/linguist/labels{/name}\",\r\n" + 
			"    \"releases_url\": \"https://api.github.com/repos/octocat/linguist/releases{/id}\",\r\n" + 
			"    \"deployments_url\": \"https://api.github.com/repos/octocat/linguist/deployments\",\r\n" + 
			"    \"created_at\": \"2016-08-02T17:35:14Z\",\r\n" + 
			"    \"updated_at\": \"2017-09-04T23:28:59Z\",\r\n" + 
			"    \"pushed_at\": \"2017-09-21T08:52:28Z\",\r\n" + 
			"    \"git_url\": \"git://github.com/octocat/linguist.git\",\r\n" + 
			"    \"ssh_url\": \"git@github.com:octocat/linguist.git\",\r\n" + 
			"    \"clone_url\": \"https://github.com/octocat/linguist.git\",\r\n" + 
			"    \"svn_url\": \"https://github.com/octocat/linguist\",\r\n" + 
			"    \"homepage\": \"\",\r\n" + 
			"    \"size\": 32899,\r\n" + 
			"    \"stargazers_count\": 10,\r\n" + 
			"    \"watchers_count\": 10,\r\n" + 
			"    \"language\": \"Ruby\",\r\n" + 
			"    \"has_issues\": false,\r\n" + 
			"    \"has_projects\": true,\r\n" + 
			"    \"has_downloads\": true,\r\n" + 
			"    \"has_wiki\": false,\r\n" + 
			"    \"has_pages\": false,\r\n" + 
			"    \"forks_count\": 21,\r\n" + 
			"    \"mirror_url\": null,\r\n" + 
			"    \"open_issues_count\": 4,\r\n" + 
			"    \"forks\": 21,\r\n" + 
			"    \"open_issues\": 4,\r\n" + 
			"    \"watchers\": 10,\r\n" + 
			"    \"default_branch\": \"master\"\r\n" + 
			"  },\r\n" + 
			"  {\r\n" + 
			"    \"id\": 17881631,\r\n" + 
			"    \"name\": \"octocat.github.io\",\r\n" + 
			"    \"full_name\": \"octocat/octocat.github.io\",\r\n" + 
			"    \"owner\": {\r\n" + 
			"      \"login\": \"octocat\",\r\n" + 
			"      \"id\": 583231,\r\n" + 
			"      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/583231?v=4\",\r\n" + 
			"      \"gravatar_id\": \"\",\r\n" + 
			"      \"url\": \"https://api.github.com/users/octocat\",\r\n" + 
			"      \"html_url\": \"https://github.com/octocat\",\r\n" + 
			"      \"followers_url\": \"https://api.github.com/users/octocat/followers\",\r\n" + 
			"      \"following_url\": \"https://api.github.com/users/octocat/following{/other_user}\",\r\n" + 
			"      \"gists_url\": \"https://api.github.com/users/octocat/gists{/gist_id}\",\r\n" + 
			"      \"starred_url\": \"https://api.github.com/users/octocat/starred{/owner}{/repo}\",\r\n" + 
			"      \"subscriptions_url\": \"https://api.github.com/users/octocat/subscriptions\",\r\n" + 
			"      \"organizations_url\": \"https://api.github.com/users/octocat/orgs\",\r\n" + 
			"      \"repos_url\": \"https://api.github.com/users/octocat/repos\",\r\n" + 
			"      \"events_url\": \"https://api.github.com/users/octocat/events{/privacy}\",\r\n" + 
			"      \"received_events_url\": \"https://api.github.com/users/octocat/received_events\",\r\n" + 
			"      \"type\": \"User\",\r\n" + 
			"      \"site_admin\": false\r\n" + 
			"    },\r\n" + 
			"    \"private\": false,\r\n" + 
			"    \"html_url\": \"https://github.com/octocat/octocat.github.io\",\r\n" + 
			"    \"description\": null,\r\n" + 
			"    \"fork\": false,\r\n" + 
			"    \"url\": \"https://api.github.com/repos/octocat/octocat.github.io\",\r\n" + 
			"    \"forks_url\": \"https://api.github.com/repos/octocat/octocat.github.io/forks\",\r\n" + 
			"    \"keys_url\": \"https://api.github.com/repos/octocat/octocat.github.io/keys{/key_id}\",\r\n" + 
			"    \"collaborators_url\": \"https://api.github.com/repos/octocat/octocat.github.io/collaborators{/collaborator}\",\r\n" + 
			"    \"teams_url\": \"https://api.github.com/repos/octocat/octocat.github.io/teams\",\r\n" + 
			"    \"hooks_url\": \"https://api.github.com/repos/octocat/octocat.github.io/hooks\",\r\n" + 
			"    \"issue_events_url\": \"https://api.github.com/repos/octocat/octocat.github.io/issues/events{/number}\",\r\n" + 
			"    \"events_url\": \"https://api.github.com/repos/octocat/octocat.github.io/events\",\r\n" + 
			"    \"assignees_url\": \"https://api.github.com/repos/octocat/octocat.github.io/assignees{/user}\",\r\n" + 
			"    \"branches_url\": \"https://api.github.com/repos/octocat/octocat.github.io/branches{/branch}\",\r\n" + 
			"    \"tags_url\": \"https://api.github.com/repos/octocat/octocat.github.io/tags\",\r\n" + 
			"    \"blobs_url\": \"https://api.github.com/repos/octocat/octocat.github.io/git/blobs{/sha}\",\r\n" + 
			"    \"git_tags_url\": \"https://api.github.com/repos/octocat/octocat.github.io/git/tags{/sha}\",\r\n" + 
			"    \"git_refs_url\": \"https://api.github.com/repos/octocat/octocat.github.io/git/refs{/sha}\",\r\n" + 
			"    \"trees_url\": \"https://api.github.com/repos/octocat/octocat.github.io/git/trees{/sha}\",\r\n" + 
			"    \"statuses_url\": \"https://api.github.com/repos/octocat/octocat.github.io/statuses/{sha}\",\r\n" + 
			"    \"languages_url\": \"https://api.github.com/repos/octocat/octocat.github.io/languages\",\r\n" + 
			"    \"stargazers_url\": \"https://api.github.com/repos/octocat/octocat.github.io/stargazers\",\r\n" + 
			"    \"contributors_url\": \"https://api.github.com/repos/octocat/octocat.github.io/contributors\",\r\n" + 
			"    \"subscribers_url\": \"https://api.github.com/repos/octocat/octocat.github.io/subscribers\",\r\n" + 
			"    \"subscription_url\": \"https://api.github.com/repos/octocat/octocat.github.io/subscription\",\r\n" + 
			"    \"commits_url\": \"https://api.github.com/repos/octocat/octocat.github.io/commits{/sha}\",\r\n" + 
			"    \"git_commits_url\": \"https://api.github.com/repos/octocat/octocat.github.io/git/commits{/sha}\",\r\n" + 
			"    \"comments_url\": \"https://api.github.com/repos/octocat/octocat.github.io/comments{/number}\",\r\n" + 
			"    \"issue_comment_url\": \"https://api.github.com/repos/octocat/octocat.github.io/issues/comments{/number}\",\r\n" + 
			"    \"contents_url\": \"https://api.github.com/repos/octocat/octocat.github.io/contents/{+path}\",\r\n" + 
			"    \"compare_url\": \"https://api.github.com/repos/octocat/octocat.github.io/compare/{base}...{head}\",\r\n" + 
			"    \"merges_url\": \"https://api.github.com/repos/octocat/octocat.github.io/merges\",\r\n" + 
			"    \"archive_url\": \"https://api.github.com/repos/octocat/octocat.github.io/{archive_format}{/ref}\",\r\n" + 
			"    \"downloads_url\": \"https://api.github.com/repos/octocat/octocat.github.io/downloads\",\r\n" + 
			"    \"issues_url\": \"https://api.github.com/repos/octocat/octocat.github.io/issues{/number}\",\r\n" + 
			"    \"pulls_url\": \"https://api.github.com/repos/octocat/octocat.github.io/pulls{/number}\",\r\n" + 
			"    \"milestones_url\": \"https://api.github.com/repos/octocat/octocat.github.io/milestones{/number}\",\r\n" + 
			"    \"notifications_url\": \"https://api.github.com/repos/octocat/octocat.github.io/notifications{?since,all,participating}\",\r\n" + 
			"    \"labels_url\": \"https://api.github.com/repos/octocat/octocat.github.io/labels{/name}\",\r\n" + 
			"    \"releases_url\": \"https://api.github.com/repos/octocat/octocat.github.io/releases{/id}\",\r\n" + 
			"    \"deployments_url\": \"https://api.github.com/repos/octocat/octocat.github.io/deployments\",\r\n" + 
			"    \"created_at\": \"2014-03-18T20:54:39Z\",\r\n" + 
			"    \"updated_at\": \"2017-07-06T04:15:11Z\",\r\n" + 
			"    \"pushed_at\": \"2017-09-21T23:28:53Z\",\r\n" + 
			"    \"git_url\": \"git://github.com/octocat/octocat.github.io.git\",\r\n" + 
			"    \"ssh_url\": \"git@github.com:octocat/octocat.github.io.git\",\r\n" + 
			"    \"clone_url\": \"https://github.com/octocat/octocat.github.io.git\",\r\n" + 
			"    \"svn_url\": \"https://github.com/octocat/octocat.github.io\",\r\n" + 
			"    \"homepage\": null,\r\n" + 
			"    \"size\": 335,\r\n" + 
			"    \"stargazers_count\": 16,\r\n" + 
			"    \"watchers_count\": 16,\r\n" + 
			"    \"language\": \"CSS\",\r\n" + 
			"    \"has_issues\": true,\r\n" + 
			"    \"has_projects\": true,\r\n" + 
			"    \"has_downloads\": true,\r\n" + 
			"    \"has_wiki\": true,\r\n" + 
			"    \"has_pages\": true,\r\n" + 
			"    \"forks_count\": 48,\r\n" + 
			"    \"mirror_url\": null,\r\n" + 
			"    \"open_issues_count\": 8,\r\n" + 
			"    \"forks\": 48,\r\n" + 
			"    \"open_issues\": 8,\r\n" + 
			"    \"watchers\": 16,\r\n" + 
			"    \"default_branch\": \"master\"\r\n" + 
			"  },\r\n" + 
			"  {\r\n" + 
			"    \"id\": 1300192,\r\n" + 
			"    \"name\": \"Spoon-Knife\",\r\n" + 
			"    \"full_name\": \"octocat/Spoon-Knife\",\r\n" + 
			"    \"owner\": {\r\n" + 
			"      \"login\": \"octocat\",\r\n" + 
			"      \"id\": 583231,\r\n" + 
			"      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/583231?v=4\",\r\n" + 
			"      \"gravatar_id\": \"\",\r\n" + 
			"      \"url\": \"https://api.github.com/users/octocat\",\r\n" + 
			"      \"html_url\": \"https://github.com/octocat\",\r\n" + 
			"      \"followers_url\": \"https://api.github.com/users/octocat/followers\",\r\n" + 
			"      \"following_url\": \"https://api.github.com/users/octocat/following{/other_user}\",\r\n" + 
			"      \"gists_url\": \"https://api.github.com/users/octocat/gists{/gist_id}\",\r\n" + 
			"      \"starred_url\": \"https://api.github.com/users/octocat/starred{/owner}{/repo}\",\r\n" + 
			"      \"subscriptions_url\": \"https://api.github.com/users/octocat/subscriptions\",\r\n" + 
			"      \"organizations_url\": \"https://api.github.com/users/octocat/orgs\",\r\n" + 
			"      \"repos_url\": \"https://api.github.com/users/octocat/repos\",\r\n" + 
			"      \"events_url\": \"https://api.github.com/users/octocat/events{/privacy}\",\r\n" + 
			"      \"received_events_url\": \"https://api.github.com/users/octocat/received_events\",\r\n" + 
			"      \"type\": \"User\",\r\n" + 
			"      \"site_admin\": false\r\n" + 
			"    },\r\n" + 
			"    \"private\": false,\r\n" + 
			"    \"html_url\": \"https://github.com/octocat/Spoon-Knife\",\r\n" + 
			"    \"description\": \"This repo is for demonstration purposes only.\",\r\n" + 
			"    \"fork\": false,\r\n" + 
			"    \"url\": \"https://api.github.com/repos/octocat/Spoon-Knife\",\r\n" + 
			"    \"forks_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/forks\",\r\n" + 
			"    \"keys_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/keys{/key_id}\",\r\n" + 
			"    \"collaborators_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/collaborators{/collaborator}\",\r\n" + 
			"    \"teams_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/teams\",\r\n" + 
			"    \"hooks_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/hooks\",\r\n" + 
			"    \"issue_events_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/issues/events{/number}\",\r\n" + 
			"    \"events_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/events\",\r\n" + 
			"    \"assignees_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/assignees{/user}\",\r\n" + 
			"    \"branches_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/branches{/branch}\",\r\n" + 
			"    \"tags_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/tags\",\r\n" + 
			"    \"blobs_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/git/blobs{/sha}\",\r\n" + 
			"    \"git_tags_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/git/tags{/sha}\",\r\n" + 
			"    \"git_refs_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/git/refs{/sha}\",\r\n" + 
			"    \"trees_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/git/trees{/sha}\",\r\n" + 
			"    \"statuses_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/statuses/{sha}\",\r\n" + 
			"    \"languages_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/languages\",\r\n" + 
			"    \"stargazers_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/stargazers\",\r\n" + 
			"    \"contributors_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/contributors\",\r\n" + 
			"    \"subscribers_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/subscribers\",\r\n" + 
			"    \"subscription_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/subscription\",\r\n" + 
			"    \"commits_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/commits{/sha}\",\r\n" + 
			"    \"git_commits_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/git/commits{/sha}\",\r\n" + 
			"    \"comments_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/comments{/number}\",\r\n" + 
			"    \"issue_comment_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/issues/comments{/number}\",\r\n" + 
			"    \"contents_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/contents/{+path}\",\r\n" + 
			"    \"compare_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/compare/{base}...{head}\",\r\n" + 
			"    \"merges_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/merges\",\r\n" + 
			"    \"archive_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/{archive_format}{/ref}\",\r\n" + 
			"    \"downloads_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/downloads\",\r\n" + 
			"    \"issues_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/issues{/number}\",\r\n" + 
			"    \"pulls_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/pulls{/number}\",\r\n" + 
			"    \"milestones_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/milestones{/number}\",\r\n" + 
			"    \"notifications_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/notifications{?since,all,participating}\",\r\n" + 
			"    \"labels_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/labels{/name}\",\r\n" + 
			"    \"releases_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/releases{/id}\",\r\n" + 
			"    \"deployments_url\": \"https://api.github.com/repos/octocat/Spoon-Knife/deployments\",\r\n" + 
			"    \"created_at\": \"2011-01-27T19:30:43Z\",\r\n" + 
			"    \"updated_at\": \"2017-09-25T04:29:24Z\",\r\n" + 
			"    \"pushed_at\": \"2017-09-25T11:25:27Z\",\r\n" + 
			"    \"git_url\": \"git://github.com/octocat/Spoon-Knife.git\",\r\n" + 
			"    \"ssh_url\": \"git@github.com:octocat/Spoon-Knife.git\",\r\n" + 
			"    \"clone_url\": \"https://github.com/octocat/Spoon-Knife.git\",\r\n" + 
			"    \"svn_url\": \"https://github.com/octocat/Spoon-Knife\",\r\n" + 
			"    \"homepage\": \"\",\r\n" + 
			"    \"size\": 1407736,\r\n" + 
			"    \"stargazers_count\": 10018,\r\n" + 
			"    \"watchers_count\": 10018,\r\n" + 
			"    \"language\": \"HTML\",\r\n" + 
			"    \"has_issues\": true,\r\n" + 
			"    \"has_projects\": true,\r\n" + 
			"    \"has_downloads\": true,\r\n" + 
			"    \"has_wiki\": true,\r\n" + 
			"    \"has_pages\": false,\r\n" + 
			"    \"forks_count\": 93921,\r\n" + 
			"    \"mirror_url\": null,\r\n" + 
			"    \"open_issues_count\": 10853,\r\n" + 
			"    \"forks\": 93921,\r\n" + 
			"    \"open_issues\": 10853,\r\n" + 
			"    \"watchers\": 10018,\r\n" + 
			"    \"default_branch\": \"master\"\r\n" + 
			"  },\r\n" + 
			"  {\r\n" + 
			"    \"id\": 56271164,\r\n" + 
			"    \"name\": \"test-repo1\",\r\n" + 
			"    \"full_name\": \"octocat/test-repo1\",\r\n" + 
			"    \"owner\": {\r\n" + 
			"      \"login\": \"octocat\",\r\n" + 
			"      \"id\": 583231,\r\n" + 
			"      \"avatar_url\": \"https://avatars3.githubusercontent.com/u/583231?v=4\",\r\n" + 
			"      \"gravatar_id\": \"\",\r\n" + 
			"      \"url\": \"https://api.github.com/users/octocat\",\r\n" + 
			"      \"html_url\": \"https://github.com/octocat\",\r\n" + 
			"      \"followers_url\": \"https://api.github.com/users/octocat/followers\",\r\n" + 
			"      \"following_url\": \"https://api.github.com/users/octocat/following{/other_user}\",\r\n" + 
			"      \"gists_url\": \"https://api.github.com/users/octocat/gists{/gist_id}\",\r\n" + 
			"      \"starred_url\": \"https://api.github.com/users/octocat/starred{/owner}{/repo}\",\r\n" + 
			"      \"subscriptions_url\": \"https://api.github.com/users/octocat/subscriptions\",\r\n" + 
			"      \"organizations_url\": \"https://api.github.com/users/octocat/orgs\",\r\n" + 
			"      \"repos_url\": \"https://api.github.com/users/octocat/repos\",\r\n" + 
			"      \"events_url\": \"https://api.github.com/users/octocat/events{/privacy}\",\r\n" + 
			"      \"received_events_url\": \"https://api.github.com/users/octocat/received_events\",\r\n" + 
			"      \"type\": \"User\",\r\n" + 
			"      \"site_admin\": false\r\n" + 
			"    },\r\n" + 
			"    \"private\": false,\r\n" + 
			"    \"html_url\": \"https://github.com/octocat/test-repo1\",\r\n" + 
			"    \"description\": null,\r\n" + 
			"    \"fork\": false,\r\n" + 
			"    \"url\": \"https://api.github.com/repos/octocat/test-repo1\",\r\n" + 
			"    \"forks_url\": \"https://api.github.com/repos/octocat/test-repo1/forks\",\r\n" + 
			"    \"keys_url\": \"https://api.github.com/repos/octocat/test-repo1/keys{/key_id}\",\r\n" + 
			"    \"collaborators_url\": \"https://api.github.com/repos/octocat/test-repo1/collaborators{/collaborator}\",\r\n" + 
			"    \"teams_url\": \"https://api.github.com/repos/octocat/test-repo1/teams\",\r\n" + 
			"    \"hooks_url\": \"https://api.github.com/repos/octocat/test-repo1/hooks\",\r\n" + 
			"    \"issue_events_url\": \"https://api.github.com/repos/octocat/test-repo1/issues/events{/number}\",\r\n" + 
			"    \"events_url\": \"https://api.github.com/repos/octocat/test-repo1/events\",\r\n" + 
			"    \"assignees_url\": \"https://api.github.com/repos/octocat/test-repo1/assignees{/user}\",\r\n" + 
			"    \"branches_url\": \"https://api.github.com/repos/octocat/test-repo1/branches{/branch}\",\r\n" + 
			"    \"tags_url\": \"https://api.github.com/repos/octocat/test-repo1/tags\",\r\n" + 
			"    \"blobs_url\": \"https://api.github.com/repos/octocat/test-repo1/git/blobs{/sha}\",\r\n" + 
			"    \"git_tags_url\": \"https://api.github.com/repos/octocat/test-repo1/git/tags{/sha}\",\r\n" + 
			"    \"git_refs_url\": \"https://api.github.com/repos/octocat/test-repo1/git/refs{/sha}\",\r\n" + 
			"    \"trees_url\": \"https://api.github.com/repos/octocat/test-repo1/git/trees{/sha}\",\r\n" + 
			"    \"statuses_url\": \"https://api.github.com/repos/octocat/test-repo1/statuses/{sha}\",\r\n" + 
			"    \"languages_url\": \"https://api.github.com/repos/octocat/test-repo1/languages\",\r\n" + 
			"    \"stargazers_url\": \"https://api.github.com/repos/octocat/test-repo1/stargazers\",\r\n" + 
			"    \"contributors_url\": \"https://api.github.com/repos/octocat/test-repo1/contributors\",\r\n" + 
			"    \"subscribers_url\": \"https://api.github.com/repos/octocat/test-repo1/subscribers\",\r\n" + 
			"    \"subscription_url\": \"https://api.github.com/repos/octocat/test-repo1/subscription\",\r\n" + 
			"    \"commits_url\": \"https://api.github.com/repos/octocat/test-repo1/commits{/sha}\",\r\n" + 
			"    \"git_commits_url\": \"https://api.github.com/repos/octocat/test-repo1/git/commits{/sha}\",\r\n" + 
			"    \"comments_url\": \"https://api.github.com/repos/octocat/test-repo1/comments{/number}\",\r\n" + 
			"    \"issue_comment_url\": \"https://api.github.com/repos/octocat/test-repo1/issues/comments{/number}\",\r\n" + 
			"    \"contents_url\": \"https://api.github.com/repos/octocat/test-repo1/contents/{+path}\",\r\n" + 
			"    \"compare_url\": \"https://api.github.com/repos/octocat/test-repo1/compare/{base}...{head}\",\r\n" + 
			"    \"merges_url\": \"https://api.github.com/repos/octocat/test-repo1/merges\",\r\n" + 
			"    \"archive_url\": \"https://api.github.com/repos/octocat/test-repo1/{archive_format}{/ref}\",\r\n" + 
			"    \"downloads_url\": \"https://api.github.com/repos/octocat/test-repo1/downloads\",\r\n" + 
			"    \"issues_url\": \"https://api.github.com/repos/octocat/test-repo1/issues{/number}\",\r\n" + 
			"    \"pulls_url\": \"https://api.github.com/repos/octocat/test-repo1/pulls{/number}\",\r\n" + 
			"    \"milestones_url\": \"https://api.github.com/repos/octocat/test-repo1/milestones{/number}\",\r\n" + 
			"    \"notifications_url\": \"https://api.github.com/repos/octocat/test-repo1/notifications{?since,all,participating}\",\r\n" + 
			"    \"labels_url\": \"https://api.github.com/repos/octocat/test-repo1/labels{/name}\",\r\n" + 
			"    \"releases_url\": \"https://api.github.com/repos/octocat/test-repo1/releases{/id}\",\r\n" + 
			"    \"deployments_url\": \"https://api.github.com/repos/octocat/test-repo1/deployments\",\r\n" + 
			"    \"created_at\": \"2016-04-14T21:29:25Z\",\r\n" + 
			"    \"updated_at\": \"2016-10-09T07:53:15Z\",\r\n" + 
			"    \"pushed_at\": \"2016-04-05T05:31:50Z\",\r\n" + 
			"    \"git_url\": \"git://github.com/octocat/test-repo1.git\",\r\n" + 
			"    \"ssh_url\": \"git@github.com:octocat/test-repo1.git\",\r\n" + 
			"    \"clone_url\": \"https://github.com/octocat/test-repo1.git\",\r\n" + 
			"    \"svn_url\": \"https://github.com/octocat/test-repo1\",\r\n" + 
			"    \"homepage\": null,\r\n" + 
			"    \"size\": 1,\r\n" + 
			"    \"stargazers_count\": 0,\r\n" + 
			"    \"watchers_count\": 0,\r\n" + 
			"    \"language\": null,\r\n" + 
			"    \"has_issues\": false,\r\n" + 
			"    \"has_projects\": true,\r\n" + 
			"    \"has_downloads\": true,\r\n" + 
			"    \"has_wiki\": true,\r\n" + 
			"    \"has_pages\": false,\r\n" + 
			"    \"forks_count\": 1,\r\n" + 
			"    \"mirror_url\": null,\r\n" + 
			"    \"open_issues_count\": 0,\r\n" + 
			"    \"forks\": 1,\r\n" + 
			"    \"open_issues\": 0,\r\n" + 
			"    \"watchers\": 0,\r\n" + 
			"    \"default_branch\": \"gh-pages\"\r\n" + 
			"  }\r\n" + 
			"]\r\n" + 
			"";
	@Test
	public void shouldParseRepositories() throws IOException, URISyntaxException {
		
		//given 
		int repoCount = 7;
		User user;
		
		//when
		List<Repository> repositoriesList = JsonHelper.parseRepositories(repositories);
		user = repositoriesList.get(0).getUser();

		//then
		assertNotNull(repositoriesList);
		assertFalse(repositoriesList.isEmpty());
		assertEquals(repositoriesList.size(),repoCount);
		assertNotNull(user);
		assertEquals(user.getUsername(),"octocat");
		
	}
	
	

}
